name: Run 12am.py

# Controls when the action will run. 
on:
  # To run 12am.py everyday at 12AM IST (18:30 UST)
  schedule:
    - cron:  '30 18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  _12am:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: installing requirements
        run: pip install sklearn requests pymongo dnspython # pandas matplotlib graphviz

      - name: run 12am.py
        run: python3 ./12am.py
